<?php

namespace RPPDb\RieselBundle\Repository;

/**
 * WorkRangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkRangeRepository extends \Doctrine\ORM\EntityRepository
{
}
