<?php

namespace RPPDb\RieselBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RieselKRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RieselKRepository extends EntityRepository
{
    public function findByRange($min, $max) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT k FROM RPPDbRieselBundle:RieselK k WHERE k.num >= :min AND k.num <= :max ORDER BY k.num ASC'
            )->setParameters(array('min' => $min, 'max' => $max))
            ->getResult();
    }
}
