<?php

namespace RPPDb\RieselBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RieselPrimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RieselPrimeRepository extends EntityRepository {
    public function findByKBelow($k, $limit) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM RPPDbRieselBundle:RieselPrime p WHERE p.n < :limit AND p.rieselK = :k ORDER BY p.n ASC'
            )->setParameters(array('k' => $k, 'limit' => $limit))
            ->getResult();
    }
    
    public function findByKAbove($k, $limit) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM RPPDbRieselBundle:RieselPrime p WHERE p.n > :limit AND p.rieselK = :k ORDER BY p.n ASC'
            )->setParameters(array('k' => $k, 'limit' => $limit))
            ->getResult();
    }
    
    public function findByRieselKAndN($rieselk, $n) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM RPPDbRieselBundle:RieselPrime p WHERE p.rieselK = :k AND p.n = :n'
            )->setParameters(array('k' => $rieselk, 'n' => $n))
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }
    
    public function findByKNumAndN($k, $n) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM RPPDbRieselBundle:RieselPrime p JOIN p.rieselK k WHERE k.num = :k AND p.n = :n'
            )->setParameters(array('k' => $k, 'n' => $n))
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }
    
    public function findWoodallPrimes() {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p, k, nw FROM RPPDbRieselBundle:RieselPrime p JOIN p.rieselk k LEFT JOIN p.nearWoodall nw WHERE p.woodall IS NOT NULL ORDER BY p.woodall ASC'
            )->getResult();
    }
    
    public function findTwinByN($n) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT k.num FROM RPPDbRieselBundle:RieselPrime p JOIN p.rieselK k WHERE p.n = :n AND p.isTwin = true ORDER BY k.num ASC'
           )->setParameters(array('n' => $n))
            ->setMaxResults(1)
            ->getResult();
    }
}
