<?php

namespace RPPDb\RieselBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WoodallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WoodallRepository extends EntityRepository
{
    public function findPrimes() {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT w, p, k, c, nw FROM RPPDbRieselBundle:Woodall w JOIN w.prime p JOIN p.rieselK k LEFT JOIN p.foundBy c LEFT JOIN p.nearWoodall nw ORDER BY w.n ASC"
            )->getResult();
    }
}
